# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ICO check
email: your-email@example.com
telegram-url: https://t.me/checkico
twitter-url: https://twitter.com/icocheckio
github-url: https://github.com/ico-check/ico-check
github-issues-url: https://github.com/ico-check/ico-check/issues
google_analytics: UA-108636813-1
ads:
  redirect_url: https://techcrunch.com/2017/07/01/invisible-unicorns-35-big-companies-that-started-with-little-or-no-money/
  # mobile leaderboard expects size 320x50
  mobile_leaderboard_url: https://i.imgur.com/gVaJbqE.jpg
  # leaderboard expects size 728x90
  leaderboard_url: https://i.imgur.com/xSmZkGB.jpg
  # large leaderboard expects size 970x90
  large_leaderboard_url: https://i.imgur.com/tVv3Ufs.jpg

  first_rectangle_ad:
    redirect_url: https://www.sec.gov/ICO
    # medium rectangle expects size 300x250
    medium_rectangle_url: https://i.imgur.com/4ykkVH6.jpg
  second_rectangle_ad:
    redirect_url: https://www.sec.gov/ICO
    # medium rectangle expects size 300x250
    medium_rectangle_url: https://i.imgur.com/RXng7ME.jpg
  third_rectangle_ad:
    redirect_url: https://www.sec.gov/ICO
    # medium rectangle expects size 300x250
    medium_rectangle_url: https://i.imgur.com/NPqL10Y.jpg
description: >- # this means to ignore newlines until "baseurl:"
  ICO-Check is a community-driven website that lists the latest ICOs and conducts due diligence on each one of them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
